# Generated by Django 2.2.12 on 2021-12-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
